name: YouTube Summarizer

on:
  schedule:
    - cron: "0 14 * * *"  # 9am EST = 14:00 UTC (冬令时)
    - cron: "0 13 * * *"  # 9am EDT = 13:00 UTC (夏令时)
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install yt-dlp
          
      - name: Configure yt-dlp for CI environment
        run: |
          mkdir -p ~/.config/yt-dlp
          echo "--no-check-certificate" > ~/.config/yt-dlp/config
          echo "--prefer-free-formats" >> ~/.config/yt-dlp/config
          echo "--extractor-retries 5" >> ~/.config/yt-dlp/config
          echo "--fragment-retries 5" >> ~/.config/yt-dlp/config
          echo "--retry-sleep 5" >> ~/.config/yt-dlp/config

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run auto_runner
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_SMTP_SERVER: ${{ secrets.EMAIL_SMTP_SERVER }}
          EMAIL_SMTP_PORT: ${{ secrets.EMAIL_SMTP_PORT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          ASSEMBLYAI_API_KEY: ${{ secrets.ASSEMBLYAI_API_KEY }}
        run: |
          python auto_runner.py